### ISSUE TITLE
Unsupported Media ?

### ISSUE THREAD

**Issue by daslicht** [didacte/videojs-vimeo#1] opened 2017-01-30 13:57 UTC
Hi,
any idea why I get an error when trying to use this video : 

https://vimeo.com/201170382

```

video.js:22933 VIDEOJS: ERROR: The "Vimeo" tech is undefined. Skipped browser support check for that tech.

video.js:22933 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
MediaError

"No compatible source was found for this media."

```

Best Regards Marc

**Comment by daslicht** [comment] 2017-01-30 14:06
Just noticed that I get that error , 'sometimes'
https://goo.gl/KtvnGq

Do you know any solution to get rid of that black flash when starting playback ?

**Comment by louim** [comment] 2017-01-31 16:25
Hey!

I tried the video url (https://vimeo.com/201170382) you provided, and it's working correctly for me in the `index.html` example. From your error, it looks like you are not including the `videojs-vimeo` script (one of those: https://github.com/didacte/videojs-vimeo/tree/master/dist).

The url in your second comment looks like this for me right now:
![capture d ecran 2017-01-31 a 11 22 44](https://cloud.githubusercontent.com/assets/923718/22473682/a3e163d6-e7a7-11e6-9078-c31088c027e7.png)
It seems like this is the same problem, the `videojs-vimeo` script is not loaded.

I'm going to close this since it's not a bug in the plugin per se, but feel free to continue the conversation if you have more details. 😄 

Cheers!

**Closed as completed by louim** 2017-01-31 16:25 UTC
